### ISSUE TITLE
Question: Personaname to Friend ID?

### ISSUE THREAD

**Issue by salacryl** [Arcana/node-dota2#303]
HI,

can I convert PersonaName to FriendID? I don't find such a function in the code.
Greetings Björn,

**Comment by Crazy-Duck** [comment]
Don't think it's possible. Persona names are not unique afaik, so it would be impossible to divine which id corresponds to one..

**Comment by salacryl** [comment]
But if I click on guy's name in a chat, the official client referse to his profile. So there must be a thing how to get to this.

**Comment by Crazy-Duck** [comment]
That's because the the object you're clicking is associated with the accountid of that user. The reborn client asks the GC the user list for the channel, which responds with a list of user objects.  Each one of those contains among others the account id and persona name of each user. The reborn client creates a panel for each user which shows the persona name, but is linked to the I'd as well. At no point does the client need to make the persona to account transformation, since both are kept in the same place. Take a look at chat.js in handlers and the protobuf related to chat. You'll see the info the client gets

**Comment by salacryl** [comment]
Ok, I can get this if people joining (regarding to onOtherJoining), but I can't get this list on my own?

**Comment by Crazy-Duck** [comment]
When your bot itself joins the chat channel, you receive a list of all people currently in the channel, it's in the response.  Then there's also the following functions (which haven't been implemented yet, so feel free to contribute): 
* `CMsgDOTAChatGetUserList` -> `k_EMsgDOTAChatGetUserList` 
* `CMsgDOTAChatGetUserListResponse` -> `k_EMsgDOTAChatGetUserListResponse`
* `CMsgClientToGCPrivateChatInfoRequest` -> `k_EMsgClientToGCPrivateChatInfoRequest` 
* `CMsgGCToClientPrivateChatInfoResponse` -> `k_EMsgClientToGCPrivateChatInfoResponse`

**Comment by Crazy-Duck** [comment]
I did some tinkering with `k_EMsgDOTAChatGetUserList` but it doesn't seem to return anything. On the other hand, node-dota2 automatically keeps track of all people joining and leaving the channel. The `chatChannels` property contains an array of all chat channels you've joined, with their current member list.
