### ISSUE TITLE
Lobby launch problem

### ISSUE THREAD

**Issue by uSide** [Arcana/node-dota2#328]
I can't start game after launchPracticeLobby() because bot not connecting to game as spectator. Can anyone help me? 
Steps to reproduce: 

- Create lobby

- Invite player to lobby

- Launch lobby

- Game fails after timeout

![screenshot](https://puu.sh/qFGO1/f5a2f75cb1.png)

```javascript
Dota2.createPracticeLobby("password", {
  "game_name": "node-dota2",
  "server_region": dota2.ServerRegion.PERFECTWORLDTELECOM,
  "game_mode": dota2.schema.DOTA_GameMode.DOTA_GAMEMODE_AR,
  "series_type": 2,
  "game_version": 1,
  "allow_cheats": false,
  "fill_with_bots": true,
  "allow_spectating": true,
  "pass_key": "password",
  "radiant_series_wins": 1,
  "dire_series_wins": 0,
  "allchat": false
}, function(err, body){
  Dota2.inviteToLobby('76561198080318845');
  setTimeout(function(){
    Dota2.joinPracticeLobbyBroadcastChannel(1, function(){
      console.log(arguments);
    });
  }, 5000);
  setTimeout(function(){
    Dota2.launchPracticeLobby();
  }, 10000);
  Dota2.on('practiceLobbyUpdate', function(){
    console.log(arguments);
  });
});
```

**Comment by Prosto-Sanja** [comment]
Cannot reproduce, bot works as unassigned player perfecly

**Comment by Prosto-Sanja** [comment]
Cannot reproduce, bot works as unassigned player perfecly
unassigned team is id 4 
`Dota2.joinPracticeLobbyTeam(2, 4);`

**Comment by Crazy-Duck** [comment]
This is 'normal' behaviour. We only interact with the GC. So if you put your bot in an actual lobby slot (i.e. spectator, broadcaster, team, ...) the game server expects them to connect to the game server on which the game will be played. Seeing as this library contains no functionality to do this, it's logical that your game will time out. If you want your lobby to actually start, you need delete the `joinPracticeLobbyBroadcastChannel` line from your code.

A general hint that has nothing to do with your issue: you might wanna hook your functionality on the events the library emits, instead of using timeouts. It's gonna make your code way les error-prone, readable and performant.

**Comment by uSide** [comment]
Thanks :+1:
