### ISSUE TITLE
Possible unintended behaviour in chat communication

### ISSUE THREAD

**Issue by UncleVasya** [Arcana/node-dota2#387]
[SendMessage()](https://github.com/Arcana/node-dota2/blob/3a16adcbca9682c766f76b2860f93df4f1081337/handlers/chat.js#L64) checks channel for `undefined `and writes "Cannot send message to a channel you have not joined." if so.  
But [_getChannelByName()](https://github.com/Arcana/node-dota2/blob/3a16adcbca9682c766f76b2860f93df4f1081337/handlers/chat.js#L21) can return both `undefined `(if no channel found with this name) and `null `(if no channels at all).

So if user tries to send message to a channel he didn't join, execution stops after check and user gets error message - good. 
But if he didn't join any channels and tries to send a message, execution will go past the check - bad.

**Comment by devilesk** [comment]
As long as code outside this library isn't setting chatChannels to a falsy value, _getChannelByName will always return either a channel data or `undefined` and never `null`.

If a user didn't join any channels [chatChannels will be an empty array](https://github.com/Arcana/node-dota2/blob/a1f51cb388b4705b4b4e1570bbe65a4809197499/index.js#L29) but it will still pass the [condition in _getChannelByName](https://github.com/Arcana/node-dota2/blob/a1f51cb388b4705b4b4e1570bbe65a4809197499/handlers/chat.js#L7) (because !![] == true) and it will return `undefined`.
