### ISSUE TITLE
Get practice lobby result with bot that abandoned at the start

### ISSUE THREAD

**Issue by angel200sdnot** [Arcana/node-dota2#395]
Is it possible to get the result from a private lobby that isn't ticketed without having to make the bot stay as a spactator/broadcaster/coach until the game is finished?

**Comment by zackcoburn** [comment]
I'm also interested in the answer to this question.

**Comment by Crazy-Duck** [comment]
Alright, since there have been like a million different tickets open for this:
As soon as you create a lobby, a match ID is assigned. You should be able to read this from the lobby updates you receive. However, details about private lobbies are __not__ publicly made available through the API, except for those who actually played them (so even if you stay in the lobby until the end as a spectator, you won't be able to get the details at a later point). This is because they are *private* lobbies. As soon as you ticket a lobby, it becomes a *public* lobby for which the details can be queried. Pro players would not be happy when their scrims were disclosed to the public, as this would evidently prevent them from saving strats for TI27

**Comment by zackcoburn** [comment]
So, is this statement correct? There is no way to get the Match ID of a lobby created through the API unless the bot creating the lobby plays in the match.

Is there a way to ticket a lobby through the API?

**Comment by Crazy-Duck** [comment]
the bot doesn't need to play, he only needs to be in the player pool afaik. Don't know about ticket, there's probably a way to do it through the createPracticeLobby settings, but I don't have any experience with that

**Comment by zackcoburn** [comment]
The 'Start game' button doesn't appear if the bot is in the unassigned player pool.

**Comment by Crazy-Duck** [comment]
let the bot create the lobby, then it's admin and can start the game

**Comment by zackcoburn** [comment]
Is there an API call that will start the game?

**Comment by Crazy-Duck** [comment]
`launchPracticeLobby` ...? It's all in the README

**Comment by zackcoburn** [comment]
I had been doing that without waiting for the other players to join, and it didn't work. It just occurred to me to try doing it after the players have joined, and now it works.  It didn't occur to me that 'launching a practice lobby' is equivalent to 'starting a game.' 👍

**Comment by Crazy-Duck** [comment]
yeah you need to wait till there's at least one real person in either team before you launch. Since the bot can't connect to the game server itself, if you launch while it's just sitting there alone, game's just gonna fail
