### ISSUE TITLE
Can bot rejoin game as assigned player?

### ISSUE THREAD

**Issue by kevinyeo92** [Arcana/node-dota2#408]
I assigned the bot in "Unassigned player" to get update from lobby game until the winner is decided. But sometime, my bot disconnect and trigger steamError due to Internet Connection. Is it possible to make the bot to rejoin the game and continue receiving updates?

**Comment by Crazy-Duck** [comment]
You'd have to try to invoke joinPracticeLobby again and see if that works, but i'm not sure if it will..

**Comment by Timsanxyz** [comment]
How can you make bot assign as "unassigned player"? I tried so hard.  I could only make bot use broadcast channel/team slot/ or be kicked)

**Comment by angel200sdnot** [comment]
@kevinyeo92 i don't know the behavior of the bot when disconnecting with an error, but you can start by adding an interval when you get the steamError to reconnect, something like
```javascript
var reconnectTimer //Initialize this var to hold the reconnect timer
onSteamLogOn = function onSteamLogOn(logonResp) {
  onSteamError = function onSteamError(error) {
    util.log("Connection closed by server.");
    reconnectTimer = setInterval(function() {
       //Here goes your reconnect function
     }, 5000);
  };

steamClient.on("connected", function() {
  steamUser.logOn(logOnDetails);
  clearInterval(reconnectTimer); //Clear the reconnect interval once reconnected
});
```
What you do next depends on whats happening, if the dota 2 client has to be restarted, restart it, if you need to rejoin an active game, use NetHook to see what happens when you press the reconnect button and replicate it with the bot

@Timsanxyz  The best way to assign the bot to "unassigned player" is by kicking himself of the slot using practiceLobbyKickFromTeam, you can also use Dota2.joinPracticeLobbyTeam(1, 4);

**Comment by Crazy-Duck** [comment]
If you want an example of how to handle disconnects, check out [node-dota2-bot](https://github.com/Arcana/node-dota2-bot) under this same organisation. It reconnects the bot whenever it loses connection and does so with a let-off function, so as not to spam Valve servers. @Timsanxyz , like angel said, you either kick the bot from the team (it can kick itself too if it's admin of the lobby) or you join team 4.

**Comment by Timsanxyz** [comment]
@angel200sdnot @Crazy-Duck Thanks a lot! connecting to 4 works for me! The problem was that practiceLobbyKickFromTeam was not only kicking from team, but from lobby too.
Now lobby starts with no error, players are playing game, but I still have one question - can I have the match_id on exiting from lobby? Or it is being generated after the game is over?
And one more - for the moment I run some php on one server, and bot runs on other server. I use ssh exec to connect from php to bot, and then bot returns some variables back, so the question is - are there any better ways to do that? I plan to run about 60-100 matches at once.
Thanks in advance for help!

**Comment by Crazy-Duck** [comment]
match_id should be obtainable from the lobby updates your bot gets while the game goes on. You can monitor the lobby state to detect the end of the match as well. As for the communication between your two servers, I'd opt for creating simple REST services either on your PHP server, to which you can post information, or on your node js server, which can takes commands. SSH exec is generally discouraged cause it opens you up for waaay too much security vulnerabiliies.

**Comment by ACmagic** [comment]
sometimes the disconnected bot would happen to miss its match result . How can we make sure bot always receive result? will the practiceLobbyUpdate be fired after match ends?
