### ISSUE TITLE
custom_game_mode

### ISSUE THREAD

**Issue by elpaxdota** [Arcana/node-dota2#437]
In readme.md custom_game_mode with status TODO. Is it working right now ? Can this library create lobby with custom game mode (like pudge wars) ?

**Comment by Crazy-Duck** [comment]
The TODO in the README signifies we still need to write the doc for that parameter, since we haven't taken the time to figure out what it takes yet :) So yes, this library is able to do just that (since we can do anything the normal client can by design) you just need to figure out *how* exactly. Try creating a lobby for pudge wars with the normal client while running nethook to figure out the parameters, then try to use those with the library

**Comment by Crazy-Duck** [comment]
README has been updated for 5.0.0
