### ISSUE TITLE
How to set "Selection Priority: Automatic (Coin Flip)"?

### ISSUE THREAD

**Issue by markrmessmore** [Arcana/node-dota2#546]
If this is in the docs I've missed it. However as I've said before I'm a n00b so that is entirely possible.

As of the July 14th update this year a setting appears in private lobbies to have selection priority be automatic (via a virtual coin flip) in the lobby between the teams themselves. I'm just not seeing the lobby setting to make that happen. Can someone point me to what I'm missing?

Thanks.

**Comment by ThomasK33** [comment]
I added the fileds in a fork.
Will try to finish up the docs and make a pull request by the end of the week.

**Comment by angel200sdnot** [comment]
Last time i checked the coin toss in Dota 2, both sides in the lobby need to have a team set, and the lobby requires a league ticket (im not sure about this one) and when i launched the lobby it didn't work, i can't remember in which way wasn't working but it made me not use that setting for my tournament system. So if you try out this setting and it works let us know here

**Comment by ThomasK33** [comment]
I’ve been successfully using auto coinflip since season 2 in EchoLeague.

There are a couple of caveats when using this priority selection option.
I will write them down clearly in a couple of hours, but basically you have to ensure that: both teams have a team set in the lobby, (if the lobby is for a game 2+ of a series: one has to ensure that the teams have the same team id as in the previous games, previous game id set and the score are set according to the outcome of the previous matches played in the series).

Yet auto coinflip does not require a ticket set (try it out by going into a 1 vs 1 mid lobby with someone else, both setting up team tags and then the host starts the selection).

**Comment by markrmessmore** [comment]
awesome. I'll be watching for the update. Thanks!

**Comment by markrmessmore** [comment]
Hey @ThomasK33 - I realize EchoLeague has just announced season 3 signups so you may be plenty busy there. Just checking to see if you have had a chance to work on those docs or at least point me in the right direction. Thanks.

**Comment by almirsarajcic** [comment]
Any updates on this?

**Comment by Prochy20** [comment]
Any update? selection_priority_rules still cannot be sent as far as I know
