### ISSUE TITLE
Retrieve previous rank in profile card

### ISSUE THREAD

**Issue by ykim** [Arcana/node-dota2#589]
I noticed that the profileCards have a new property to get previous rank. Is it possible to update the protobuf in the current library to retrieve this data?

**Comment by ykim** [comment]
@Crazy-Duck : Thanks! Btw, do you think there is a way to automate updates when a new protobuf is released to take care of these kinds of issues?

**Comment by Crazy-Duck** [comment]
I've been thinking about it recently but I haven't found a way yet :/ The issue is that if something changes in the protobufs that breaks compatibility it will break things.. Too be honest I think the best way to go about it would be to find a way to automatically generate the various functions straight from the protobuf definitions. That way if they change, the method definitions would get updated automatically as well. I *think* @paralin has done something similar in go, but I haven't looked at it in detail yet

**Comment by Crazy-Duck** [comment]
New version pushed to npm, should be fine now.
