### ISSUE TITLE
Upgrade to ECMAScript 6

### ISSUE THREAD

**Issue by matheuschagas** [Arcana/node-dota2#594]
Hello, I'm a developer and I need to know if you are interested in upgrade the project's ECMAScript. If yes I can help. 

We can improve the requests using `async await` thing, using Promises and so one.

**Comment by pendo324** [comment]
It might be helpful to provide some more details on what exactly would you want to change. The only things I can think of right now are using ES6 classes instead of util.inherits() for Dota2Client in `index.js`, and maybe changing a few less important things, like using `const` and `let` instead of `var`. Other than that, there's only one handler that uses Promises, and one example that uses Promises.

Anyway, those aren't major changes, and wouldn't take long to implement. If you really want to do it, it might be better to just submit a pull request and see if it gets accepted. I'd be interested in helping you out if you could provide some more details.
