### ISSUE TITLE
Is it possible to override 50 req/day for MatchDetails?

### ISSUE THREAD

**Issue by 0x366** [Arcana/node-dota2#666]
Hello, I need to download a lot of replay_salts - and the 50req/day is bringing that down. Is there some way to increase this limit? 

Thanks

**Comment by 8q16d** [comment]
I have the same issue. Maybe one of the [CMsgClientLogon](https://github.com/SteamDatabase/Protobufs/blob/master/steam/steammessages_clientserver_login.proto) properties has a way to bypass this, since the limit is tied to the Steam user login, but I can't find any documentation for it and brute forcing would take a while.

**Comment by 0x366** [comment]
hm, are you sure that "limit is tied to the Steam user login" ?

**Comment by jimmydorry** [comment]
There are two distinct rate limits. Per user and per IP. Obviously the IP rate limit is higher than the user one, but not massively higher.

And no, you don't get exemptions. Even the very large dota organisations just have to work around it, last I spoke to one of them.

**Comment by 0x366** [comment]
Correct me if wrong, but the only way to get a lot of replay salts, using this repo, is to register a lot of accounts and get a lot of proxies ?
